[project]
name = "pygame-gui"
version = "0.1.0"
description = "A GUI library for pygame"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "coloredlogs>=15.0.1",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
